version: '3.8'

services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "55432:5432"